version: "3.9"
services:
  admin-frontend:
    container_name: admin_front
    # image: raityupiyo/cs-admin-frontend:latest
    build:
      context: admin_front/
      target: dev
    command: "yarn dev"
    ports:
      - 3100:3000
    volumes:
      - ./admin_front:/app
      - af_nodemodules:/app/node_modules

  end-frontend:
    container_name: end_front
    # image: raityupiyo/cs-end-frontend:latest
    build:
      context: end_front/
      target: dev
    command: "yarn dev"
    ports:
      - 3200:3000
    volumes:
      - ./end_front:/app
      - ef_nodemodules:/app/node_modules

  admin-backend:
    container_name: admin_back
    # image: cs-admin-backend:latest
    build:
      context: admin_back/
      target: dev
    command: "yarn dev"
    ports:
      - 9100:9000
    volumes:
      - ./admin_back:/app
      - ab_nodemodules:/app/node_modules

  end-backend:
    container_name: end_back
    build:
      context: admin_back/
      target: dev
    # image: cs-end-backend:latest
    command: "yarn dev"
    ports:
      - 9200:9000
    volumes:
      - ./end_back:/app
      - eb_nodemodules:/app/node_modules

  mysql:
    container_name: mysql
    image: mariadb:10.5
    ports:
      - 33060:3306
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .database.env

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    env_file:
      - .database.env
volumes:
  database:
  ab_nodemodules:
  af_nodemodules:
  eb_nodemodules:
  ef_nodemodules: